[package]
name = "uttt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttt-rs = { git = "https://github.com/hwoy/ttt-rs.git" }
ttt-io-rs = { git = "https://github.com/hwoy/ttt-io-rs.git" }

